sudo: false

language: php

php:
  - 5.5

before_script:
  - composer self-update
  - composer install
  - mkdir data
  - php bin/testconsole.php jackalope:init:dbal --force

script: 
  - phpunit
  - ! 'php ./vendor/bin/phpbench run tests/Bench/BenchmarkBench.php --report=''{"name": "console_table", "aggregate_iterations": true, "memory": true, "revolutions": true}'''

notifications:
  slack:
    secure: "Gd3/1e0pBKvJv1UhWpBkWijJpmSWlarg6uPBJO0h4z1IpkZjd++jOjhmOQ7n+yMfuapQuJTcVOK0yIWu7orJoGAKFkBlMEIrLk1xMAG9phjjMLUO0FWgcQ3eVW5mTyfMBtClz4OL5wXckw17ohtXHDK8qnI0Hz9Qj8Rqgf2OZhM="
